@php
    use App\Helpers\CommonHelper;
@endphp
@extends('layouts.posLayouts')

@section('content')
    <style>
        .product-card {
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            min-height: 350px;
            /* Adjust based on content */
            height: 100%;
            /* Ensures consistency */
            padding: 15px;
            border: 0.5px solid #ccc;
            border-radius: 10px;
            margin: 10px;
        }

        .product-image {
            height: 150px;
            /* Set fixed height */
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .product-image img {
            max-height: 100%;
            object-fit: contain;
            /* Prevents distortion */
        }

        .card-body {
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            height: 100%;

        }

        .variant-buttons {
            margin-top: auto;
            /* Pushes buttons to bottom */
        }


        .product-card:hover {
            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
            transform: scale(1.02);
        }

        .product-image img {
            max-width: 100px;
            height: auto;
            object-fit: contain;
        }

        .product-category {
            font-size: 0.9rem;
            margin-bottom: 5px;
            color: #666;
        }

        .product-price {
            font-size: 1.2rem;
        }

        .quantity-selector {
            margin-top: 10px;
        }

        .quantity-selector button {
            border-radius: 50%;
            width: 30px;
            height: 30px;
            border: 1px solid #ccc;
        }

        .variant-buttons .variant-button {
            border-radius: 20px;
            padding: 5px 10px;
            font-size: 0.9rem;
            transition: 0.2s ease;
        }

        .variant-buttons .variant-button:hover {
            background-color: #007bff;
            color: white;
        }

        // befor all the css was generated by ch
        .product-card:hover {
            transform: scale(1.05);
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            transition: all 0.3s ease;
        }

        .cardBody {
            border: 1px solid #ccc;
            margin-left: 10px;
            border-radius: 6px;
            box-shadow: 0 0 8px rgb(0 0 0 / 25%);
        }

        .cardHeading {
            font-size: 16px;
            text-align: center;
            font-weight: bold;
            color: #000;
            border-bottom: 1px #ccc solid;
            padding: 12px;
        }

        .cardContent {
            padding: 13px;
            text-align: center;
            font-size: 18px;
        }

        .scroll-container {
            height: 400px;
            overflow-y: auto;
            border: 1px solid #ddd;
            padding-right: 5px;
        }

        .scrollable-list {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        .scrollable-list .list-group-item {
            text-align: center;
        }

        .category-container {
            width: 100%;
            padding: 10px;
        }

        .category-logo {
            width: 80%;
            margin-bottom: 10px;
        }

        .category-list {
            padding: 0;
            list-style: none;
        }

        .category-item {
            margin-bottom: 10px;
            text-align: center;
            border: none;
        }

        .category-btn {
            display: flex;
            align-items: center;
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            background-color: white;
            border-radius: 10px;
            transition: 0.3s;
        }

        .category-btn:hover,
        .category-btn.active {
            border: 2px solid orange;
            background-color: #f8f8f8;
        }

        .category-icon {
            width: 30px;
            height: 30px;
            margin-right: 10px;
        }

        .category-text {
            font-size: 14px;
            font-weight: bold;
            color: #333;
        }

        .category-btn {
            display: flex;
            align-items: center;
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            background-color: white;
            border-radius: 10px;
            transition: 0.3s;
        }

        .category-btn:hover,
        .category-btn.active {
            border: 2px solid orange;
            background-color: #f8f8f8;
        }

        .qty-btn {
            width: 30px;
            height: 30px;
            line-height: 20px;
            text-align: center;
            border-radius: 50%;
            font-size: 16px;
            border: none;
        }

        .qty-btn:hover {
            opacity: 0.8;
        }

        .remove-btn {
            background: none;
            border: none;
            color: red;
            font-size: 18px;
            cursor: pointer;
        }
    </style>
    <div class="well_N">
        <div class="boking-wrp dp_sdw">
            <div class="row align-items-center mb-3">
                <div class="col-lg-6">
                    {{ CommonHelper::displayPageTitle('Add New POS') }}
                </div>
                <div class="col-lg-6 text-right">
                    <a href="#" class="btn btn-success mr-2" onclick="loadSalesData('today')">Today Sale</a>
                    <a href="#" class="btn btn-warning" onclick="loadSalesData('last-month')">Last Month Sale</a>
                </div>

                <!-- Add modal -->
                <div class="modal fade" id="salesModal" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="salesModalTitle">Sales Details</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body" id="salesModalBody">
                                Loading...
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="row">
                <!-- Category and Products Sections -->
                <div class="col-lg-2">
                    <div class="well">
                        <div class="cardBody" style="width: 22rem;">
                            <div class="cardHeading">Categories</div>
                            <div class="scroll-container">
                                <ul class="list-group list-group-flush scrollable-list">
                                    @foreach ($categoryList as $calRow)
                                        <li class="list-group-item category-item">
                                            <button class="category-btn" data-id="{{ $calRow->id }}">
                                                <img src="{{ asset($calRow->icon_image) }}"
                                                    alt="{{ $calRow->name }}" class="category-icon">
                                                <span class="category-text">{{ $calRow->name }}</span>
                                            </button>
                                        </li>
                                    @endforeach

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Product List Section -->
                <div class="col-lg-5">
                    <div class="well">
                        <div class="product-list">
                            <h4>Products</h4>
                            <div id="product-container">
                                <div class="row">
                                    @foreach ($products as $index => $product)
                                        <div class="col-lg-4 col-md-6 mb-4">
                                            <div class="card product-card text-center shadow-sm p-3">
                                                <div class="card-body">
                                                    <!-- Product Image -->
                                                    <div class="product-image mb-3">
                                                        {!! CommonHelper::display_document_two($product['product_image'] ?? 'assets/img/no_image.png') !!}
                                                    </div>

                                                    <!-- Product Details -->
                                                    <p class="product-category text-muted">
                                                        {{ $product['category_name'] ?? 'Category' }}</p>
                                                    <h5 class="card-title font-weight-bold">{{ $product['name'] }}</h5>
                                                    <p class="product-price font-weight-bold text-primary">
                                                        ${{ number_format($product['variants'][0]['amount'] ?? 0, 2) }}
                                                    </p>

                                                    <!-- Variant Buttons -->
                                                    <div class="variant-buttons mt-3">
                                                        @foreach ($product['variants'] as $variant)
                                                            <button
                                                                class="btn btn-outline-primary btn-sm variant-button add-to-cart mt-1"
                                                                data-product-id="{{ $product['id'] }}"
                                                                data-variant-id="{{ $variant['id'] }}"
                                                                data-barcode="{{ $variant['variant_barcode'] }}"
                                                                data-name="{{ $product['name'] }} ({{ $variant['size_name'] }})"
                                                                data-price="{{ $variant['amount'] }}">
                                                                {{ $variant['size_name'] }} -
                                                                ${{ number_format($variant['amount'], 2) }}
                                                            </button>
                                                        @endforeach
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Customer and Payment Section -->
                <div class="col-lg-5">
                    <div class="row">
                        <div class="col-lg-6">
                            <label>Customer Name</label>
                            <select name="customer_id" id="customer_id" class="form-control select2">
                                <option value="">Select Customer</option>
                                @foreach ($customerList as $clRow)
                                    <option value="{{ $clRow->id }}">{{ $clRow->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-lg-6">
                            <label>Order Date</label>
                            <input type="date" name="order_date" id="order_date" class="form-control"
                                value="{{ date('Y-m-d') }}" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <label>Product Type</label>
                            <select id="product-type" class="form-control mb-3">
                                <option value="retail">Retail</option>
                                <option value="wholesale">Wholesale</option>
                            </select>
                        </div>
                        <div class="col-lg-6">
                            <label>Barcode</label>
                            <input type="text" id="barcode-scanner" class="form-control mb-3"
                                placeholder="Scan Barcode Here" autofocus>
                        </div>
                    </div>
                    <div class="calculator p-3 border rounded shadow-sm">
                        <h4>Shopping Cart</h4>
                        <table class="table align-middle" id="cart-list">
                            <thead>
                                <tr>
                                    <th>Item</th>
                                    <th class="text-center">QTY</th>
                                    <th class="text-end">Cost</th>
                                </tr>
                            </thead>
                            <tbody id="cart-items">
                                <!-- Items will be added dynamically here -->
                            </tbody>
                        </table>
                    </div>
                    <table class="table table-bordered table-striped table-condensed">
                        <tbody>
                            <tr>
                                <th>Total:</th>
                                <td class="text-right"><span id="total-amount">0.00</span></td>
                            </tr>
                            <tr>
                                <td>
                                    <label>Payment Type</label>
                                    <select name="payment_type" id="payment_type" class="form-control">
                                        <option value="1">Cash Payment</option>
                                        <option value="2">Bank Payment</option>
                                    </select>
                                </td>
                                <td id="loadAccountsDependPaymentType"></td>
                            </tr>
                            <tr>
                                <th>Payment Amount:</th>
                                <td class="text-right"><input type="number" id="payment-amount"
                                        class="form-control mb-2" placeholder="Enter payment amount"></td>
                            </tr>
                            <tr>
                                <td colspan="2" class="text-right">
                                    <button id="calculate-change" class="btn btn-success btn-block">Calculate
                                        Change</button>
                                </td>
                            </tr>
                            <tr>
                                <th>Change:</th>
                                <td class="text-right"><span id="change-amount">0.00</span></td>
                            </tr>
                            <tr>
                                <td colspan="2" class="text-right">
                                    <button id="save-transaction" class="btn btn-primary btn-block mt-3">Save
                                        Transaction</button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        const ROUTES = {
            todaySales: "{{ route('pos.today-sales') }}",
            lastMonthSales: "{{ route('pos.last-month-sales') }}"
        };

        function loadSalesData(period) {
            console.log('Loading sales data for ' + period);
            let url = period === 'today' ? ROUTES.todaySales : ROUTES.lastMonthSales;

            $.ajax({
                url: url,
                method: 'GET',
                success: function(response) {
                    if (response.success) {
                        let content = `<h4>${response.period} Sales</h4>
                             <p>Total Orders: ${response.order_count}</p>
                             <p>Total Sales: Rs. ${parseFloat(response.total_sales).toLocaleString()}</p>`;
                        $('#salesModalBody').html(content);
                        $('#salesModalTitle').text(`${response.period} Sales Details`);
                        $('#salesModal').modal('show');
                    } else {
                        $('#salesModalBody').html('Error fetching data. first one');
                        $('#salesModal').modal('show');
                    }
                },
                error: function() {
                    $('#salesModalBody').html('Error fetching data.');
                    $('#salesModal').modal('show');
                }
            });
        }
        $(document).ready(function() {

            let cart = [];

            // Update Cart
            function updateCart() {
                let cartTable = document.getElementById("cart-items");
                cartTable.innerHTML = "";

                let totalAmount = 0; // Initialize total amount to 0

                cart.forEach((item, index) => {
                    // Calculate the price of the item (price * quantity)
                    let itemTotal = item.price * item.qty;
                    totalAmount += itemTotal; // Add it to the total amount

                    cartTable.innerHTML += `
                        <tr>
                            <td>
                                <button class="remove-btn" onclick="removeItem(${index})">🗑</button> 
                                ${item.name}
                            </td>
                            <td class="text-center">
                                <button class="btn btn-sm btn-secondary qty-btn" onclick="updateQty(${index}, -1)">-</button>
                                ${item.qty}
                                <button class="btn btn-sm btn-secondary qty-btn" onclick="updateQty(${index}, 1)">+</button>
                            </td>
                            <td class="text-end">$${itemTotal.toLocaleString()}</td>
                        </tr>
                    `;
                });

                // Update the total amount in the UI  
                $('#total-amount').text(totalAmount.toFixed(2)); // Set the total amount (formatted to two decimals)
            }

            // Add to cart
            $(document).on('click', '.add-to-cart', function() {
                let product = {
                    id: $(this).data('product-id'),
                    variantId: $(this).data('variant-id'),
                    name: $(this).data('name'),
                    price: parseFloat($(this).data('price')),
                    barcode: $(this).data('barcode'),
                    qty: 1
                };
                let exists = cart.find(p => p.id === product.id && p.variantId === product.variantId);
                if (exists) exists.qty++;
                else cart.push(product);

                updateCart();
            });

            // Barcode scanner input
            $('#barcode-scanner').on('input', function() {
                let barcode = $(this).val().trim();
                let product = $('.add-to-cart').filter(function() {
                    return $(this).data('barcode') === barcode;
                }).first();
                if (product.length) product.click();
                $(this).val('');
            });

            // Update Quantity
            window.updateQty = function(index, change) {
                if (cart[index].qty + change > 0) {
                    cart[index].qty += change;
                    updateCart();
                }
            };

            // Remove Item
            window.removeItem = function(index) {
                cart.splice(index, 1);
                updateCart();
            };

            // Calculate Change
            $('#calculate-change').on('click', function() {
                let total = parseFloat($('#total-amount').text());
                let payment = parseFloat($('#payment-amount').val());
                let change = payment - total;
                $('#change-amount').text(change >= 0 ? change.toFixed(2) : 'Insufficient Amount');
            });

            // Save Transaction
            $('#save-transaction').on('click', function() {
                let total = parseFloat($('#total-amount').text());
                let paymentAmount = parseFloat($('#payment-amount').val());
                let paymentAccount = parseFloat($('#paymentAccount').val());
                let changeAmount = parseFloat($('#change-amount').text());

                if (isNaN(paymentAmount) || paymentAmount < total) {
                    alert("Insufficient payment amount.");
                    return;
                }

                let cartItems = cart.map(item => ({
                    productId: item.id,
                    variantId: item.variantId,
                    name: item.name,
                    price: item.price,
                    qty: item.qty,
                    discount: item.discount || 0
                }));

                let data = {
                    customerId: $('#customer_id').val(),
                    paymentType: $('#payment_type').val(),
                    orderDate: $('#order_date').val(),
                    productType: $('#product-type').val(),
                    cart: cartItems,
                    totalAmount: total,
                    paymentAmount: paymentAmount,
                    paymentAccount: paymentAccount,
                    changeAmount: changeAmount
                };

                // Save to server
                $.ajax({
                    url: "{{ route('pos.store') }}",
                    method: "POST",
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    data: JSON.stringify(data),
                    success: function(response) {
                        if (response.success) {
                            alert('Transaction Saved!');
                            // Reset form and cart
                            $('#customer_id').val('');
                            $('#payment_type').val('');
                            $('#payment-amount').val('');
                            $('#total-amount').text('0.00');
                            $('#change-amount').text('0.00');
                            cart = [];
                            updateCart();
                        } else {
                            alert('Error saving transaction: ' + (response.message ||
                                'Please try again.'));
                        }
                    },
                    error: function() {
                        alert('There was an error saving the transaction.');
                    }
                });
            });

            // Load accounts based on payment type
            function loadAccountsDependPaymentType() {
                var paymentType = $('#payment_type').val();
                var baseUrl = $("#url").val();
                $('#loadAccountsDependPaymentType').html('');
                $.ajax({
                    url: "" + baseUrl + "/pos/loadAccountsDependPaymentType",
                    method: "GET",
                    data: {
                        paymentType: paymentType,
                    },
                    error: function() {
                        alert("error");
                    },
                    success: function(response) {
                        $('#loadAccountsDependPaymentType').html(response);
                    }
                });
            }

            loadAccountsDependPaymentType();

            // Category filter functionality

            let selectedCategories = [];

            $(".category-btn").on("click", function() {
                let categoryId = $(this).data("id");

                // Toggle selection
                if ($(this).hasClass("active")) {
                    $(this).removeClass("active");
                    selectedCategories = selectedCategories.filter(id => id !== categoryId);
                } else {
                    $(this).addClass("active");
                    selectedCategories.push(categoryId);
                }

                // Send the updated selected categories list via AJAX
                $.ajax({
                    url: "{{ route('pos.filterProducts') }}",
                    method: "POST",
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    data: {
                        categories: selectedCategories
                    },
                    success: function(response) {
                        $('#product-container').html(response);
                    },
                    error: function(xhr) {
                        console.error("Error fetching products", xhr);
                    }
                });
            });
        });
    </script>
@endsection
